# SPDX-FileCopyrightText: 2025-2026 NORCE Research AS
# SPDX-License-Identifier: GPL-3.0
# pylint: disable=C0302,R0902,R0913,R0914,R0917,R1702,R0912,R0915,E1102,C0321

"""Utiliy script for creating a deck with projected pressures from given
regional and site decks"""

import csv
import os
import sys
from contextlib import nullcontext
from dataclasses import dataclass

import numpy as np
from alive_progress import alive_bar
from numpy.typing import NDArray
from opm.io.ecl import EclFile as OpmFile
from opm.io.ecl import EGrid as OpmGrid
from opm.io.ecl import ERst as OpmRestart
from scipy.interpolate import LinearNDInterpolator, interp1d
from scipy.spatial import cKDTree
from shapely.geometry import LineString, Point, Polygon

HEADER = (
    "-- Copyright (C) 2025-2026 NORCE Research AS\n"
    "-- This deck was generated by expreccs https://github.com/cssr-tools/expreccs\n"
)

# fmt: off
@dataclass(slots=True)
class Regional:
    """Regional variables"""
    grid: OpmGrid
    init: OpmFile
    rst: OpmRestart
    rfip: NDArray
    act: NDArray
    rdays: NDArray


@dataclass(slots=True)
class Site:
    """Site variables"""
    grid: OpmGrid
    init: OpmFile
    rst: OpmRestart
    sfip: NDArray
    sdata: str

@dataclass(slots=True)
class Config:
    """Config variables"""
    fol: str
    fsit: str
    explicit: bool
    zones: bool
    freq: NDArray
    acoeff: NDArray
    boundaries: list[int]
    nonregular: bool

@dataclass(slots=True)
class InterpData:
    """Interpolation variables"""
    ri: list[NDArray]; rx: list[NDArray]; ry: list[NDArray]; rz: list[NDArray]
    sx: list[list[float]]; sy: list[list[float]]; sz: list[list[float]]
    rf: list[NDArray]; rk: list[NDArray]; rt: list[NDArray]; rkg: list[list[tuple[float, int]]]
    sf: list[list[int]]; st: list[list[float]]
    sai: list[int]; snum: list[int]

@dataclass(slots=True)
class XYMaps:
    """XYMaping variables"""
    x_i: NDArray
    y_i: NDArray
    z_i: NDArray
    inds: list[int]
    fipr: NDArray
    offset: list[float]
    oprn: NDArray
    rtmin: float

@dataclass(slots=True)
class BCCon:
    """Boundary variables"""
    coords: list[list[float]]
    sbound: list[str]
    spres: list[float]
    ksfips: list[int]
    stmin: float
    sopn: NDArray

@dataclass(slots=True)
class Borders:
    """Border variables"""
    sx: list[list[float]]; sy: list[list[float]]; sz: list[list[float]]
    sf: list[list[int]]; st: list[list[float]]
    sbound: list[str]
    sai: list[int]

@dataclass(slots=True)
class RegionalCells:
    """Regional variables"""
    ri:list;rx:list;ry:list;rz:list
    rf:list[NDArray];rt:list;rk:list;rkg: list[list[tuple[float, int]]]
    sbound:list[str]

@dataclass(slots=True)
class SiteBorders:
    """Site variables"""    
    spres: list[float]
    sai: list[int]
    sbound: list[str]
    sxn: list[float]; syn: list[float]; szn: list[float]; sfn: list[int]; stn: list[float]
    sxw: list[float]; syw: list[float]; szw: list[float]; sfw: list[int]; stw: list[float]
    sxs: list[float]; syl: list[float]; szs: list[float]; sfs: list[int]; sts: list[float]
    sxe: list[float]; sye: list[float]; sze: list[float]; sfe: list[int]; ste: list[float]
# fmt: on


def create_deck(
    fol: str,
    explicit: bool,
    zones: bool,
    freq: NDArray,
    nonregular: bool,
    acoeff: NDArray,
    boundaries: list[int],
    reg: str,
    freg: str,
    sit: str,
    fsit: str,
) -> None:
    """Main orchestration of the hirerchical expreccs approach"""
    if zones:
        explicit = False

    case = f"{freg}/{reg}"
    rrst, rgrid = OpmRestart(case + ".UNRST"), OpmGrid(case + ".EGRID")
    rinit = OpmFile(case + ".INIT")

    case = f"{fsit}/{sit}"
    srst, sgrid, sinit = (
        OpmRestart(case + ".UNRST"),
        OpmGrid(case + ".EGRID"),
        OpmFile(case + ".INIT"),
    )
    sdata = case + ".DATA"

    rdim, sdim = rgrid.dimension, sgrid.dimension
    rfip = np.ones(np.prod(rdim))
    sfip = np.ones(np.prod(sdim))
    ufip = np.array([1])

    ract = np.array(rinit["PORV"]) > 0
    if zones:
        rfip = np.array(rinit["FIPNUM"])
        sfip = np.array(sinit["FIPNUM"])
        ufip = np.intersect1d(np.unique(rfip), np.unique(sfip))

    rdays = np.array([rrst["DOUBHEAD", i][0] for i in range(len(rrst))])
    sdays = np.array([rrst["DOUBHEAD", i][0] for i in range(len(rrst))])
    isdays = np.array([rrst["DOUBHEAD", i][0] for i in range(len(rrst))])

    site = Site(sgrid, sinit, srst, sfip, sdata)
    regional = Regional(rgrid, rinit, rrst, rfip, ract, rdays)

    if len(freq) < len(isdays) - 2:
        freq = np.array([int(freq[0])] * (len(isdays) - 1))
    else:
        freq = np.array([int(v) for v in freq])

    if len(acoeff) < len(isdays) - 2:
        acoeff = np.array([float(acoeff[0])] * (len(isdays) - 1))
    else:
        acoeff = np.array([float(v) for v in acoeff])

    if np.max(freq) <= 0:
        sdays = np.array([])

    sopn = np.zeros(np.prod(sdim))

    if not os.path.exists(fol):
        os.makedirs(fol, exist_ok=True)
    if not os.path.exists(f"{fol}/bc") and np.max(freq) > 0:
        os.makedirs(fol + "/bc", exist_ok=True)

    mly, mlx = find_ij_orientation(sgrid)

    rp: list[list[tuple[int, float]]] = [[] for _ in range(len(rrst))]

    if nonregular:
        start_point = []
        actnum = np.array(sinit["PORV"]) > 0
        if sdim[2] == 1:
            grid = actnum.reshape(sdim[1], sdim[0])
        else:
            tmp0 = []
            for j in range(sdim[1]):
                for i in range(sdim[0]):
                    tmp0.append(0)
                    for k in range(sdim[2]):
                        ind = i + j * sdim[0] + k * sdim[0] * sdim[1]
                        if actnum[ind] > 0:
                            tmp0[-1] = 1
                            break
            grid = np.array(tmp0).reshape(sdim[1], sdim[0])
        for j in range(sdim[1]):
            for i in range(sdim[0]):
                if grid[j][i]:
                    start_point = [j, i]
                    break
            if start_point:
                break
        boundary, dire = site_contour(grid, start_point)

        bc = get_bccon(
            site, regional, boundaries, explicit, np.array(boundary), dire, sopn
        )

        coords = bc.coords
        sbound = bc.sbound
        spres = bc.spres
        ksfips = bc.ksfips
        stmin = bc.stmin
        sopn = bc.sopn

        xy = get_xymaps(regional, ufip, zones, coords)

        x_i = xy.x_i
        y_i = xy.y_i
        z_i = xy.z_i
        inds = xy.inds
        fipr = xy.fipr
        offset = xy.offset
        oprn = xy.oprn
        rtmin = xy.rtmin

        with open(f"{freg}/OPERNUM_EXPRECCS.INC", "w", encoding="utf8") as f:
            f.write(HEADER)
            f.write("OPERNUM\n")
            f.write("".join(compact_format_numeric(oprn)))
            f.write("/\n")

        tmp = sbound.copy()
        if sbound:
            print("Dynamic interpolator:")
        z0 = np.array(rrst["PRESSURE", 0])
        coords_arr = np.array(coords)

        with alive_bar(len(rrst)) as bar_animation:
            for i in range(len(rrst)):
                if not sbound:
                    break
                bar_animation()
                z_p_full = np.array(rrst["PRESSURE", i])
                if not explicit:
                    z_p = (z_p_full - z0)[inds]
                else:
                    if rrst.count("WAT_DEN", i):
                        den = 9.81 * rrst["WAT_DEN", i] / 1e5
                    else:
                        den = 9.81 * 1000.0 * (z_p_full > 0) / 1e5
                    z_p = np.array(
                        [
                            z_p_full[ind] + den[ind] * offset[j]
                            for j, ind in enumerate(inds)
                        ]
                    )

                count, n = 0, -1
                interp = LinearNDInterpolator(list(zip(x_i, y_i, z_i)), z_p)
                coords_eval = coords_arr.copy()
                if zones:
                    coords_eval[:, 2] += np.round(rtmin - stmin, 2)

                vals = interp(coords_eval)

                for idx, _ in enumerate(coords):
                    edit = sbound[count].split() if i == 0 else tmp[count].split()
                    val = vals[idx]
                    if zones:
                        zone_key = ksfips[int(edit[5]) - 1]
                        if n != zone_key:
                            n = zone_key
                            whr = fipr == n
                            if np.any(whr):
                                interp = LinearNDInterpolator(
                                    list(zip(x_i[whr], y_i[whr], z_i[whr])), z_p[whr]
                                )
                                vals = interp(coords_eval)
                        if not np.any(whr):
                            if i == 0:
                                sopn[
                                    sgrid.global_index(
                                        int(edit[1]) - 1,
                                        int(edit[3]) - 1,
                                        int(edit[5]) - 1,
                                    )
                                ] = -1
                                sbound.pop(count)
                                if not explicit:
                                    spres.pop(count)
                        else:
                            if not np.isnan(val):
                                count += 1
                                rp[i].append((count, val))
                                if i == 0:
                                    edit[0] = str(count)
                                    sbound[count - 1] = " ".join(edit)
                            else:
                                if i == 0:
                                    sopn[
                                        sgrid.global_index(
                                            int(edit[1]) - 1,
                                            int(edit[3]) - 1,
                                            int(edit[5]) - 1,
                                        )
                                    ] = -1
                                    sbound.pop(count)
                                    if not explicit:
                                        spres.pop(count)
                    else:
                        if not np.isnan(val):
                            count += 1
                            rp[i].append((count, val))
                            if i == 0:
                                edit[0] = str(count)
                                sbound[count - 1] = " ".join(edit)
                        else:
                            if i == 0:
                                sopn[
                                    sgrid.global_index(
                                        int(edit[1]) - 1,
                                        int(edit[3]) - 1,
                                        int(edit[5]) - 1,
                                    )
                                ] = -1
                                sbound.pop(count)
                                if not explicit:
                                    spres.pop(count)

    else:
        sb = extract_site_borders(
            sgrid, sdim, sinit, srst, boundaries, explicit, mly, mlx, sfip
        )

        spres = sb.spres

        borders = Borders(
            [sb.sxn, sb.sxw, sb.sxs, sb.sxe],
            [sb.syn, sb.syw, sb.syl, sb.sye],
            [sb.szn, sb.szw, sb.szs, sb.sze],
            [sb.sfn, sb.sfw, sb.sfs, sb.sfe],
            [sb.stn, sb.stw, sb.sts, sb.ste],
            sb.sbound,
            sb.sai,
        )

        rc, snum = find_regional_cells(
            rgrid, sgrid, sinit, rinit, rfip, zones, borders, ract
        )

        sbound = rc.sbound

        data = InterpData(
            rc.ri,
            rc.rx,
            rc.ry,
            rc.rz,
            [sb.sxn, sb.sxw, sb.sxs, sb.sxe],
            [sb.syn, sb.syw, sb.syl, sb.sye],
            [sb.szn, sb.szw, sb.szs, sb.sze],
            rc.rf,
            rc.rk,
            rc.rt,
            rc.rkg,
            [sb.sfn, sb.sfw, sb.sfs, sb.sfe],
            [sb.stn, sb.stw, sb.sts, sb.ste],
            sb.sai,
            snum,
        )

        nsteps = len(rrst)
        rp = [[] for _ in range(nsteps)]

        print("Dynamic interpolator:")
        show_progress = sys.stdout.isatty()
        if show_progress:
            bar_ctx = alive_bar(nsteps, bar="fish")
        else:
            bar_ctx = nullcontext()
        with bar_ctx as bar_animation:
            for i in range(nsteps):
                if show_progress:
                    bar_animation()
                rp_i, sbound = project_pressures(
                    rrst, rgrid, sgrid, data, sbound, ufip, explicit, zones, sopn, i
                )
                rp[i] = rp_i

    sdays, ddays, sbc = temporal_interpolation(
        freq, acoeff, sdays, isdays, rdays, rp, explicit, spres
    )

    write_files(fol, fsit, freq, ddays, sdata, sbound, sbc, sdays, sopn)


def get_xymaps(
    regional: Regional,
    ufip: NDArray,
    zones: bool,
    coords: list[list[float]],
) -> XYMaps:
    """Get the coordinates"""
    rgrid = regional.grid
    rinit = regional.init
    rfip = regional.rfip

    fipr, x_i, y_i, z_i, inds, offset = [], [], [], [], [], []
    rtmin = np.inf
    rdim = rgrid.dimension
    nxyz = np.prod(rdim)
    oprn = np.zeros(nxyz, dtype=int)
    actnum = np.array(rinit["PORV"]) > 0
    nact = sum(actnum)

    c_x = np.empty(nact, dtype=float)
    c_y = np.empty(nact, dtype=float)
    c_z = np.empty(nact, dtype=float)
    act_inds = np.empty(nact, dtype=int)

    nxyz = np.prod(rdim)
    x = np.empty(nxyz, dtype=float)
    y = np.empty(nxyz, dtype=float)
    z = np.empty(nxyz, dtype=float)
    n, ind = 0, 0
    for k in range(rdim[2]):
        for j in range(rdim[1]):
            for i in range(rdim[0]):
                x[ind], y[ind], z[ind] = np.mean(
                    rgrid.xyz_from_ijk(i, j, k, True), axis=1
                )
                if actnum[ind]:
                    c_x[n] = x[ind]
                    c_y[n] = y[ind]
                    c_z[n] = z[ind]
                    act_inds[n] = ind
                    n += 1
                ind += 1
    act_inds = np.array(act_inds)
    tree = cKDTree(np.column_stack((c_x, c_y, c_z)))
    dz = 0.5 * np.array(rinit["DZ"])
    act = actnum
    inds_set = set()

    for coord in coords:
        _, idx = tree.query(coord)
        ind = act_inds[idx]
        ijk = rgrid.ijk_from_global_index(ind)

        if not act[ind] or (zones and rfip[idx] not in ufip):
            continue

        take = [False, False, False, False, False]

        if idx not in inds_set:
            take[0] = True
            x_i.append(x[ind])
            y_i.append(y[ind])
            z_i.append(z[ind] - dz[idx])
            offset.append(-dz[idx])
            inds.append(idx)
            inds_set.add(idx)
            fipr.append(rfip[idx])
            oprn[ind] = 1

        if ijk[0] < rdim[0] - 1:
            tmp = rgrid.active_index(ijk[0] + 1, ijk[1], ijk[2])
            if tmp not in inds_set:
                take[1] = True
                oprn[ind + 1] = 1
                x_i.append(x[ind + 1])
                y_i.append(y[ind + 1])
                z_i.append(z[ind + 1] - dz[tmp])
                offset.append(-dz[tmp])
                inds.append(tmp)
                inds_set.add(tmp)
                fipr.append(rfip[tmp])

        if 0 < ijk[0]:
            tmp = rgrid.active_index(ijk[0] - 1, ijk[1], ijk[2])
            if tmp not in inds_set:
                take[2] = True
                oprn[ind - 1] = 1
                x_i.append(x[ind - 1])
                y_i.append(y[ind - 1])
                z_i.append(z[ind - 1] - dz[tmp])
                offset.append(-dz[tmp])
                inds.append(tmp)
                inds_set.add(tmp)
                fipr.append(rfip[tmp])

        if 0 < ijk[1]:
            tmp = rgrid.active_index(ijk[0], ijk[1] - 1, ijk[2])
            if tmp not in inds_set:
                take[3] = True
                oprn[ind - rdim[0]] = 1
                x_i.append(x[ind - rdim[0]])
                y_i.append(y[ind - rdim[0]])
                z_i.append(z[ind - rdim[0]] - dz[tmp])
                offset.append(-dz[tmp])
                inds.append(tmp)
                inds_set.add(tmp)
                fipr.append(rfip[tmp])

        if ijk[1] < rdim[1] - 1:
            tmp = rgrid.active_index(ijk[0], ijk[1] + 1, ijk[2])
            if tmp not in inds_set:
                take[4] = True
                oprn[ind + rdim[0]] = 1
                x_i.append(x[ind + rdim[0]])
                y_i.append(y[ind + rdim[0]])
                z_i.append(z[ind + rdim[0]] - dz[tmp])
                offset.append(-dz[tmp])
                inds.append(tmp)
                inds_set.add(tmp)
                fipr.append(rfip[tmp])

        if take[0]:
            x_i.append(x[ind])
            y_i.append(y[ind])
            z_i.append(z[ind] + dz[idx])
            offset.append(dz[idx])
            inds.append(tmp)
            fipr.append(rfip[idx])

        if take[1]:
            tmp = rgrid.active_index(ijk[0] + 1, ijk[1], ijk[2])
            x_i.append(x[ind + 1])
            y_i.append(y[ind + 1])
            z_i.append(z[ind + 1] + dz[tmp])
            offset.append(dz[tmp])
            inds.append(tmp)
            fipr.append(rfip[tmp])

        if take[2]:
            tmp = rgrid.active_index(ijk[0] - 1, ijk[1], ijk[2])
            x_i.append(x[ind - 1])
            y_i.append(y[ind - 1])
            z_i.append(z[ind - 1] + dz[tmp])
            offset.append(dz[tmp])
            inds.append(tmp)
            fipr.append(rfip[tmp])

        if take[3]:
            x_i.append(x[ind - rdim[0]])
            y_i.append(y[ind - rdim[0]])
            z_i.append(z[ind - rdim[0]] + dz[tmp])
            offset.append(dz[tmp])
            inds.append(tmp)
            fipr.append(rfip[tmp])

        if take[4]:
            tmp = rgrid.active_index(ijk[0], ijk[1] + 1, ijk[2])
            x_i.append(x[ind + rdim[0]])
            y_i.append(y[ind + rdim[0]])
            z_i.append(z[ind + rdim[0]] + dz[tmp])
            offset.append(dz[tmp])
            inds.append(tmp)
            fipr.append(rfip[tmp])

    if zones and z_i:
        rtmin = np.min(z_i)

    return XYMaps(
        np.array(x_i),
        np.array(y_i),
        np.array(z_i),
        inds,
        np.array(fipr),
        offset,
        oprn,
        rtmin,
    )


def get_bccon(
    site: Site,
    regional: Regional,
    boundaries: list[int],
    explicit: bool,
    boundary: NDArray,
    dire: list[int],
    sopn: NDArray,
) -> BCCon:
    """Handle the boundary"""
    sgrid = site.grid
    sinit = site.init
    srst = site.rst
    sfip = site.sfip

    rgrid = regional.grid
    rinit = regional.init
    rfip = regional.rfip

    coords, spres = [], []
    krfips: list[int] = []
    ksfips: list[int] = []

    stmin = np.inf
    sdim = sgrid.dimension
    act = np.array(sinit["PORV"]) > 0

    dx, dy, dz = 1.0 * act, 1.0 * act, 1.0 * act
    dx[act] = sinit["DX"]
    dy[act] = sinit["DY"]
    dz[act] = sinit["DZ"]

    sbound = []

    for k in range(sdim[2]):
        for i, val in enumerate(boundary):
            ind = int(val[0] * sdim[0] + val[1] + k * sdim[0] * sdim[1])
            if not act[ind]:
                continue
            if dire[i] == 1 and boundaries[2] == -1 and val[0] == sdim[1] - 1:
                continue
            if dire[i] == 2 and boundaries[3] == -1 and val[1] == 0:
                continue
            if dire[i] == 3 and boundaries[0] == -1 and val[0] == 0:
                continue
            if dire[i] == 4 and boundaries[1] == -1 and val[1] == sdim[0] - 1:
                continue

            sopn[ind] = dire[i]
            xyz = np.mean(sgrid.xyz_from_ijk(val[1], val[0], k, True), axis=1)

            if k == 0:
                stmin = min(stmin, xyz[2] - 0.5 * dz[ind])

            if dire[i] == 1:
                coords.append([xyz[0], xyz[1] + 0.5 * dy[ind], xyz[2]])
                sbound.append(
                    f"{i+1} {val[1]+1} {val[1]+1} {val[0]+1} {val[0]+1} {k+1} {k+1} 'J' /"
                )
            elif dire[i] == 2:
                coords.append([xyz[0] - 0.5 * dx[ind], xyz[1], xyz[2]])
                sbound.append(
                    f"{i+1} {val[1]+1} {val[1]+1} {val[0]+1} {val[0]+1} {k+1} {k+1} 'I-' /"
                )
            elif dire[i] == 3:
                coords.append([xyz[0], xyz[1] - 0.5 * dy[ind], xyz[2]])
                sbound.append(
                    f"{i+1} {val[1]+1} {val[1]+1} {val[0]+1} {val[0]+1} {k+1} {k+1} 'J-' /"
                )
            elif dire[i] == 4:
                coords.append([xyz[0] + 0.5 * dx[ind], xyz[1], xyz[2]])
                sbound.append(
                    f"{i+1} {val[1]+1} {val[1]+1} {val[0]+1} {val[0]+1} {k+1} {k+1} 'I' /"
                )

            if not explicit:
                inda = sgrid.active_index(val[1], val[0], k)
                spres.append(srst["PRESSURE", 0][inda])

    if not explicit:
        for gridn, initn, fip_arr, kfips in [
            (rgrid, rinit, rfip, krfips),
            (sgrid, sinit, sfip, ksfips),
        ]:
            dimn = gridn.dimension
            actn = np.array(initn["PORV"]) > 0
            for k in range(dimn[2]):
                for j in range(dimn[1]):
                    for i in range(dimn[0]):
                        ind = i + j * dimn[0] + k * dimn[0] * dimn[1]
                        inda = gridn.active_index(i, j, k)
                        if actn[ind] and len(kfips) == k:
                            kfips.append(fip_arr[inda])
                            break
                    if len(kfips) == k + 1:
                        break
                if len(kfips) == k:
                    kfips.append(-1)

    return BCCon(coords, sbound, spres, ksfips, stmin, sopn)


def site_contour(
    grid: NDArray,
    start: list[int],
) -> tuple[list[list[int]], list[int]]:
    """Process the site contour"""
    directions = [(-1, -1), (-1, 0), (-1, 1), (0, 1), (1, 1), (1, 0), (1, -1), (0, -1)]
    boundary, dire = [], []
    current = start
    backtrack_dir = 7
    start_backtrack = backtrack_dir
    first = True
    nrows, ncols = len(grid), len(grid[0])
    while True:
        boundary.append(current)
        found = False
        for i in range(8):
            dir_idx = (backtrack_dir + 1 + i) % 8
            dr, dc = directions[dir_idx]
            nr, nc = current[0] + dr, current[1] + dc
            if 0 <= nr < nrows and 0 <= nc < ncols and grid[nr][nc]:
                if len(boundary) == 1:
                    if current[0] == 0 or not grid[current[0] - 1][current[1]]:
                        dire.append(2)
                    elif (
                        current[0] == nrows - 1 or not grid[current[0] + 1][current[1]]
                    ):
                        dire.append(4)
                    elif current[1] == 0 or not grid[current[0]][current[1] - 1]:
                        dire.append(3)
                    elif (
                        current[1] == ncols - 1 or not grid[current[0]][current[1] + 1]
                    ):
                        dire.append(1)
                current = [nr, nc]
                backtrack_dir = (dir_idx + 6) % 8
                if dir_idx in [0, 7]:
                    dire.append(1)
                elif dir_idx in [1, 2]:
                    dire.append(2)
                elif dir_idx in [3, 4]:
                    dire.append(3)
                else:
                    dire.append(4)
                found = True
                break
        if not found:
            break
        if current == start and backtrack_dir == start_backtrack and not first:
            break
        first = False
    return boundary, dire


def compact_format_numeric(v: NDArray) -> list[str]:
    "To 'n*x' notation"
    change_idx = np.flatnonzero(np.diff(v, prepend=v[0] - 1))
    counts = np.diff(np.append(change_idx, v.size))
    vals = v[change_idx]

    out = []
    for val, n in zip(vals, counts):
        val_str = str(int(val)) if float(val).is_integer() else str(val)
        out.append(f"{n}*{val_str} " if n > 1 else f"{val_str} ")
    return out


def handle_grid_coord(
    sgrid: OpmGrid,
    rgrid: OpmGrid,
    sinit: OpmFile,
    rinit: OpmFile,
) -> tuple[NDArray, NDArray, NDArray, NDArray, NDArray, int, int, list[list[float]]]:
    """Handle the grid coordinates"""
    sdim = sgrid.dimension
    rdim = rgrid.dimension
    x0y0 = sgrid.xyz_from_ijk(0, 0, 0, True)
    xny0 = sgrid.xyz_from_ijk(sdim[0] - 1, 0, 0, True)
    xnyn = sgrid.xyz_from_ijk(sdim[0] - 1, sdim[1] - 1, 0, True)
    x0yn = sgrid.xyz_from_ijk(0, sdim[1] - 1, 0, True)
    sbox = [
        [x0y0[0][0], x0y0[1][0]],
        [xny0[0][1], xny0[1][1]],
        [xnyn[0][3], xnyn[0][3]],
        [x0yn[0][2], x0yn[1][2]],
    ]
    sbox += [sbox[0]]
    nact = np.sum(sinit["PORV"][: sdim[0] * sdim[1]] > 0)
    s_x = np.empty(nact, dtype=float)
    s_y = np.empty(nact, dtype=float)
    act_inds = np.empty(nact, dtype=int)
    c_x = np.empty(rgrid.active_cells, dtype=float)
    c_y = np.empty(rgrid.active_cells, dtype=float)
    c_z = np.empty(rgrid.active_cells, dtype=float)
    poly = Polygon(
        [
            (sbox[0][0], sbox[0][1]),
            (sbox[1][0], sbox[1][1]),
            (sbox[2][0], sbox[2][1]),
            (sbox[3][0], sbox[3][1]),
        ]
    )
    idx_counter = 0
    for j in range(sdim[1]):
        for i in range(sdim[0]):
            if sgrid.active_index(i, j, 0) > -1:
                xyz = np.mean(sgrid.xyz_from_ijk(i, j, 0, True), axis=1)
                s_x[idx_counter] = xyz[0]
                s_y[idx_counter] = xyz[1]
                act_inds[idx_counter] = idx_counter
                idx_counter += 1
    tree = cKDTree(np.column_stack((s_x, s_y)))
    dsz = 0.5 * sinit["DZ"]
    drz = 0.5 * rinit["DZ"]
    nxyz = np.prod(rdim)
    fipn = np.ones(nxyz, dtype=int)
    oprn = np.zeros(nxyz, dtype=int)
    n, g = 0, 0
    for k in range(rdim[2]):
        for j in range(rdim[1]):
            for i in range(rdim[0]):
                if rgrid.active_index(i, j, k) > -1:
                    xyz = np.mean(rgrid.xyz_from_ijk(i, j, k, True), axis=1)
                    c_x[g] = xyz[0]
                    c_y[g] = xyz[1]
                    c_z[g] = xyz[2]
                    point = Point(xyz[0], xyz[1])
                    if poly.contains(point):
                        _, idx = tree.query([xyz[0], xyz[1]])
                        ind = int(act_inds[idx])
                        ijk = sgrid.ijk_from_active_index(ind)
                        z_t = np.mean(
                            sgrid.xyz_from_ijk(ijk[0], ijk[1], ijk[2], True), axis=1
                        )[2]
                        z_b = np.mean(
                            sgrid.xyz_from_ijk(
                                ijk[0], ijk[1], ijk[2] + sdim[2] - 1, True
                            ),
                            axis=1,
                        )[2]
                        fipn[n] = k + 2
                        d_z = drz[rgrid.active_index(i, j, k)]
                        if (
                            c_z[-1] + d_z >= z_t - dsz[ind]
                            and c_z[-1] - d_z <= z_b + dsz[ind]
                        ):
                            oprn[n] = 1
                        else:
                            oprn[n] = 7
                    g += 1
                n += 1
    rnxy = rdim[0] * rdim[1]
    rnxyz = rnxy * rdim[2]
    return fipn, oprn, c_x, c_y, c_z, rnxy, rnxyz, sbox


def check_regional_neighbours(
    rgrid: OpmGrid,
    ract: NDArray,
    rfip: NDArray,
    rnxy: int,
    ri: list[int],
    rx: list[float],
    ry: list[float],
    rz: list[float],
    rk: list[int],
    rf: list[int],
    rt: list[float],
    gind: int,
    n: int,
    d_z: NDArray,
    oprn: NDArray,
) -> NDArray:
    """Check the regional neighbours"""
    rdim = rgrid.dimension
    ijk = rgrid.ijk_from_global_index(gind)
    noise = -1e-4 * np.random.rand() if rdim[2] > 1 else 0

    def add_neigh(gtmp, ijk_n, kval):
        if gtmp < 0 or gtmp >= rnxy * rdim[2] or not ract[gtmp]:
            return
        tmp = rgrid.active_index(ijk_n[0], ijk_n[1], ijk_n[2])
        if tmp in ri:
            return
        xyz = np.mean(rgrid.xyz_from_ijk(ijk_n[0], ijk_n[1], ijk_n[2], True), axis=1)
        rx.append(xyz[0])
        ry.append(xyz[1])
        rz.append(noise + xyz[2])
        ri.append(tmp)
        rk.append(kval)
        rf.append(rfip[tmp])
        rt.append(xyz[2] - d_z[tmp])
        oprn[gtmp] = 2 + n if int(oprn[gtmp]) == 2 + n else 6

    if ijk[1] - 1 >= 0:
        add_neigh(gind - rdim[0], (ijk[0], ijk[1] - 1, ijk[2]), ijk[2])
    if ijk[1] + 1 < rdim[1]:
        add_neigh(gind + rdim[0], (ijk[0], ijk[1] + 1, ijk[2]), ijk[2])
    if ijk[0] - 1 >= 0:
        add_neigh(gind - 1, (ijk[0] - 1, ijk[1], ijk[2]), ijk[2])
    if ijk[0] + 1 < rdim[0]:
        add_neigh(gind + 1, (ijk[0] + 1, ijk[1], ijk[2]), ijk[2])
    if gind - rnxy >= 0:
        add_neigh(gind - rnxy, (ijk[0], ijk[1], ijk[2] - 1), ijk[2] - 1)
    if gind + rnxy < rnxy * rdim[2]:
        add_neigh(gind + rnxy, (ijk[0], ijk[1], ijk[2] + 1), ijk[2] + 1)

    return oprn


def find_regional_cells(
    rgrid: OpmGrid,
    sgrid: OpmGrid,
    sinit: OpmFile,
    rinit: OpmFile,
    rfip: NDArray,
    zones: bool,
    borders: Borders,
    ract: NDArray,
) -> tuple[RegionalCells, list[int]]:
    """Find the regional cells"""
    sx, sy, sz, sf = borders.sx, borders.sy, borders.sz, borders.sf
    sbound = borders.sbound
    sai = borders.sai
    snum = []
    sdel = []

    fipn, oprn, c_x, c_y, c_z, rnxy, rnxyz, sbox = handle_grid_coord(
        sgrid, rgrid, sinit, rinit
    )
    coords_all = np.stack((c_x, c_y, c_z), axis=1)
    tree = cKDTree(coords_all)

    ntot = 0
    for d in range(4):
        ntot += len(sx[d])

    print("\nFind the regional cells to build the interpolator:")

    ri: list[list[int]] = [[], [], [], []]
    rx: list[list[float]] = [[], [], [], []]
    ry: list[list[float]] = [[], [], [], []]
    rz: list[list[float]] = [[], [], [], []]
    rf: list[list[int]] = [[], [], [], []]
    rt: list[list[float]] = [[], [], [], []]
    rk: list[list[int]] = [[], [], [], []]
    rkg: list[list[tuple[float, int]]] = [[], [], [], []]

    count = -1
    d_z = 0.5 * rinit["DZ"]

    show_progress = sys.stdout.isatty()
    if show_progress:
        bar_ctx = alive_bar(ntot, bar="fish")
    else:
        bar_ctx = nullcontext()

    with bar_ctx as bar_animation:
        for d in range(4):
            sx_d, sy_d, sz_d, sf_d = sx[d], sy[d], sz[d], sf[d]
            ri_d, rx_d, ry_d, rz_d = ri[d], rx[d], ry[d], rz[d]
            rf_d, rt_d, rk_d = rf[d], rt[d], rk[d]

            fin = None
            tree_local: cKDTree = cKDTree(np.zeros((1, 3)))  # arbitrary initialization
            index_map: NDArray = np.array([], dtype=int)

            for i, (x_c, y_c, z_c) in enumerate(zip(sx_d, sy_d, sz_d)):
                if show_progress:
                    bar_animation()

                if zones:
                    if fin != sf_d[i]:
                        fin = sf_d[i]
                        mask = rfip == fin
                        if not np.any(mask):
                            count += 1
                            sdel.append(count)
                            continue
                        coords_local = coords_all[mask]
                        index_map = np.where(mask)[0]
                        tree_local = cKDTree(coords_local)

                    _, idx_local = tree_local.query([x_c, y_c, z_c])
                    ind = int(index_map[int(idx_local)])
                else:
                    _, ind = tree.query([x_c, y_c, z_c])
                    ind = int(ind)

                count += 1
                ijk = rgrid.ijk_from_active_index(ind)
                gind = rgrid.global_index(ijk[0], ijk[1], ijk[2])

                sdim = rgrid.dimension
                if i > [sdim[0], sdim[1], sdim[0], sdim[0]][d]:
                    lift = -1e-4
                else:
                    lift = 1e-4
                xyz = np.mean(rgrid.xyz_from_active_index(ind, True), axis=1)
                rkg[d].append((xyz[2] + lift, ind))
                lines = []
                for shift in [rgrid.dimension[0], 1]:
                    x_l, y_l, x_p, y_p = 0, 0, 0, 0
                    l_p = [0, 0]
                    x_m = xyz[0]
                    y_m = xyz[1]
                    if gind - shift >= 0 and ract[gind - shift]:
                        ijk = rgrid.ijk_from_global_index(gind - shift)
                        xyz_l = np.mean(
                            rgrid.xyz_from_ijk(ijk[0], ijk[1], ijk[2], True), axis=1
                        )
                        x_l = xyz_l[0]
                        y_l = xyz_l[1]
                        l_p[0] = 1
                    if gind + shift < rnxyz and ract[gind + shift]:
                        ijk = rgrid.ijk_from_global_index(gind + shift)
                        xyz_p = np.mean(
                            rgrid.xyz_from_ijk(ijk[0], ijk[1], ijk[2], True), axis=1
                        )
                        x_p = xyz_p[0]
                        y_p = xyz_p[1]
                        l_p[1] = 1
                    if l_p[0] and l_p[1]:
                        lines.append(LineString([(x_l, y_l), (x_p, y_p)]))
                    elif l_p[1]:
                        lines.append(LineString([(x_m, y_m), (x_p, y_p)]))
                    elif l_p[0]:
                        lines.append(LineString([(x_l, y_l), (x_m, y_m)]))
                    else:
                        lines.append(0)

                if lines[0] == 0 and lines[1] == 0:
                    sdel.append(count)
                    continue

                border = LineString(
                    [(sbox[d][0], sbox[d][1]), (sbox[d + 1][0], sbox[d + 1][1])]
                )

                if lines[0] == 0:
                    lines[0] = lines[1]
                elif lines[1] == 0:
                    lines[1] = lines[0]

                if lines[0].intersects(border) or lines[1].intersects(border):
                    ijk = rgrid.ijk_from_global_index(gind)
                    xyz = np.mean(rgrid.xyz_from_active_index(ind, True), axis=1)

                    snum.append(sai[count])
                    rx_d.append(xyz[0])
                    ry_d.append(xyz[1])
                    rz_d.append(xyz[2])
                    ri_d.append(ind)
                    rf_d.append(rfip[ind])
                    rt_d.append(rz_d[-1] - d_z[int(ind)])
                    rk_d.append(ijk[2])

                    oprn[gind] = d + 2
                    oprn = check_regional_neighbours(
                        rgrid,
                        ract,
                        rfip,
                        rnxy,
                        ri_d,
                        rx_d,
                        ry_d,
                        rz_d,
                        rk_d,
                        rf_d,
                        rt_d,
                        gind,
                        d,
                        d_z,
                        oprn,
                    )
                else:
                    sdel.append(count)

    for rem in reversed(sdel):
        del sbound[rem]

    with open("OPERNUM_EXPRECCS.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("OPERNUM\n")
        f.write("".join(compact_format_numeric(oprn)))
        f.write("/\n")

    with open("FIPNUM_EXPRECCS.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("FIPNUM\n")
        f.write("".join(compact_format_numeric(fipn)))
        f.write("/\n")

    return (
        RegionalCells(
            [np.array(v) for v in ri],
            [np.array(v) for v in rx],
            [np.array(v) for v in ry],
            [np.array(v) for v in rz],
            [np.array(v) for v in rf],
            [np.array(v) for v in rt],
            [np.array(v) for v in rk],
            rkg,
            sbound,
        ),
        snum,
    )


def temporal_interpolation(
    freq: NDArray,
    acoeff: NDArray,
    sdays: NDArray,
    isdays: NDArray,
    rdays: NDArray,
    rp: list[list[tuple[int, float]]],
    explicit: bool,
    spres: list[float],
) -> tuple[NDArray, NDArray, list[str]]:
    """Temporal interpolator"""
    if np.max(freq) > 0:
        ddays = sdays[1:] - sdays[:-1]
        idays = []
        for i, day in enumerate(sdays[:-1]):
            freq_val = freq[i]
            dd = ddays[i]
            if acoeff[i] != 0:
                telsc = np.flip(
                    (np.exp(np.flip(np.linspace(0, acoeff[i], freq_val + 1))) - 1)
                    / (np.exp(acoeff[i]) - 1)
                )
                for n in range(freq_val):
                    idays.append(day + dd * telsc[n])
            else:
                for n in range(freq_val):
                    idays.append(day + dd * n / freq_val)
        idays.append(sdays[-1])
        sdays = np.array(idays)
        ddays = sdays[1:] - sdays[:-1]
    else:
        ddays = []
    print(f"\nInput report steps regional (days, tot={len(rdays)}):")
    print(rdays)
    print(f"Input report steps site (days, tot={len(isdays)}):")
    print(isdays)
    print(f"Report steps site to write bc (days, tot={len(sdays)}):")
    print([float(f"{val:.2f}") for val in sdays])
    nsteps = len(sdays)
    sbc = ["" for _ in range(nsteps)]
    nrp = len(rp[0])
    for i in range(nrp):
        values = [rp[j][i][1] for j in range(len(rdays))]
        interp_func = interp1d(rdays, values, fill_value="extrapolate")
        index_val = rp[0][i][0]
        for j, time in enumerate(sdays):
            val = interp_func(time)
            if explicit:
                sbc[j] += f"{index_val} DIRICHLET WATER 1* {val} /\n"
            else:
                pres = val + spres[index_val - 1]
                sbc[j] += f"{index_val} DIRICHLET WATER 1* {pres} /\n"
    return sdays, ddays, sbc


def project_pressures(
    rrst: OpmRestart,
    rgrid: OpmGrid,
    sgrid: OpmGrid,
    data: InterpData,
    sbound: list[str],
    ufip: NDArray,
    explicit: bool,
    zones: bool,
    sopn: NDArray,
    i: int,
) -> tuple[list[tuple[int, float]], list[str]]:
    """Project the pressures"""
    ri, rx, ry, rz = data.ri, data.rx, data.ry, data.rz
    sx, sy, sz = data.sx, data.sy, data.sz
    rf, rk, rt, rkg = data.rf, data.rk, data.rt, data.rkg
    sf, st = data.sf, data.st
    sai, snum = data.sai, data.snum

    count, c_c, s_s, d_t, whr = 0, 1, 0, 0, 0
    snum_set = set(snum)
    pressure0 = np.array(rrst["PRESSURE", 0])
    rp_out: list[tuple[int, float]] = []

    def update_boundary(key, z_b):
        nonlocal sbound, c_c, s_s
        if not np.isnan(z_b):
            rp_out.append((key, z_b))
            for j, row in enumerate(sbound):
                edit = row.split()
                if int(edit[0]) == key:
                    if i == 0:
                        edit[0] = str(key if rgrid.dimension[2] > 1 else c_c + s_s)
                        sbound[j] = " ".join(edit)
                        sopn[
                            sgrid.global_index(
                                int(edit[1]) - 1, int(edit[3]) - 1, int(edit[5]) - 1
                            )
                        ] = 2
                    c_c += 1
                    break
        else:
            if i == 0:
                sbound = [row for row in sbound if int(row.split()[0]) != key]
                s_s += 1

    for d in range(4):
        ri_d, rx_d, ry_d, rz_d = ri[d], rx[d], ry[d], rz[d]
        sx_d, sy_d, sz_d = sx[d], sy[d], sz[d]
        rf_d, rk_d, rt_d, rkg_d = rf[d], rk[d], rt[d], rkg[d]
        sf_d, st_d = sf[d], st[d]

        n = 0
        if len(ri_d) == 0:
            nx = len(sx_d)
            count += nx
            c_c += nx + s_s
            s_s = 0
            continue

        z_p_full = np.array(rrst["PRESSURE", i])
        z_p = z_p_full[ri_d]
        w_d = np.array(rrst["WAT_DEN", i])

        if not explicit:
            z_p -= pressure0[ri_d]

        if rgrid.dimension[2] > 1:
            if not zones:
                interp = LinearNDInterpolator(list(zip(rx_d, ry_d, rz_d)), z_p)

            for k, (x, y, z) in enumerate(zip(sx_d, sy_d, sz_d)):
                sai_val = sai[count]
                key = sai_val + 1

                if sai_val in snum_set:
                    if zones:
                        sf_val = sf_d[k]
                        if sf_val in ufip:
                            if n != sf_val:
                                n = sf_val
                                whr = rf_d == n
                                if not np.any(whr):
                                    count += 1
                                    continue
                                uniq = np.unique(rk_d[whr])
                                if len(uniq) == 1:
                                    interp = LinearNDInterpolator(
                                        list(zip(rx_d[whr], ry_d[whr])), z_p[whr]
                                    )
                                else:
                                    whs = sf_d == n
                                    d_t = np.round(
                                        np.min(rt_d[whr]) - np.min(st_d[whs]), 2
                                    )
                                    interp = LinearNDInterpolator(
                                        list(zip(rx_d[whr], ry_d[whr], rz_d[whr])),
                                        z_p[whr],
                                    )

                            if len(np.unique(rk_d[whr])) == 1:
                                z_b = interp((x, y))
                            else:
                                z_b = interp((x, y, z + d_t))
                                if np.isnan(z_b):
                                    z_b = interp((x, y, rkg_d[k][0]))
                        else:
                            if i == 0:
                                sbound = [
                                    row for row in sbound if int(row.split()[0]) != key
                                ]
                                s_s += 1
                            count += 1
                            continue
                    else:
                        z_b = interp((x, y, z))
                        if np.isnan(z_b):
                            if not explicit:
                                z_b = interp((x, y, rkg_d[k][0]))
                            else:
                                z_b = (
                                    interp((x, y, rkg_d[k][0]))
                                    + (z - rkg_d[k][0]) * w_d[rkg_d[k][1]] * 9.81 / 1e5
                                )

                    update_boundary(key, z_b)

                count += 1
        else:
            interp = LinearNDInterpolator(list(zip(rx_d, ry_d)), z_p)

            for k, (x, y) in enumerate(zip(sx_d, sy_d)):
                sai_val = sai[count]
                key = sai_val + 1

                if sai_val in snum_set:
                    z_b = interp((x, y))
                    update_boundary(key, z_b)

                count += 1

    return rp_out, sbound


def write_files(
    fol: str,
    fsit: str,
    freq: NDArray,
    ddays: NDArray,
    sdata: str,
    sbound: list[str],
    sbc: list[str],
    sdays: NDArray,
    sopn: NDArray,
) -> None:
    """Write the deck and include files"""
    freq_max = np.max(freq)
    if fsit != fol:
        files = [f for f in os.listdir(fsit) if f.endswith(".INC")]
        for file in files:
            os.system(f"scp -r {fsit}/{file} {fol}")
    fre, tstep, count = 0, 0, 1
    lol = []
    with open(sdata, "r", encoding="utf8") as f:
        for line in csv.reader(f):
            nrwo = str(line)[2:-2]
            if "\t" in nrwo:
                nrwo = nrwo.replace("\t", " ")
            lol.append(nrwo)
            if nrwo == "GRID" and freq_max > 0:
                lol.append("INCLUDE")
                lol.append("'BCCON.INC' /")
            if nrwo == "REGIONS":
                lol.append("INCLUDE")
                lol.append("'OPERNUM_EXPRECCS.INC' /")
    out_path = f"{fol}/{fol.split('/')[-1].upper()}.DATA"
    n_lol = len(lol)
    lines = []
    for i, row in enumerate(lol):
        if i < n_lol - 1:
            nxt = lol[i + 1]
            if nxt == "TSTEP" and freq_max > 0:
                rep_line = lol[i + 2]
                rep_split = rep_line.split("*")
                rep = int(rep_split[0]) if len(rep_split) > 1 else 1
                lines.append(row + "\n")
                for _ in range(rep):
                    fval = freq[fre]
                    for _ in range(fval):
                        lines.append("INCLUDE\n")
                        lines.append(f"'bc/BCPROP{count}.INC' /\n")
                        lines.append("TSTEP\n")
                        lines.append(f"{ddays[count-1]} /\n")
                        count += 1
                        tstep = 1
                    fre += 1
            elif tstep == 0:
                lines.append(row + "\n")
            else:
                edit = row.split()
                if edit and (edit[-1] == "/" or edit[0] == "/"):
                    tstep = 0
        else:
            if tstep == 0:
                lines.append(row)
    with open(out_path, "w", encoding="utf8") as f:
        f.write("".join(lines))
    if freq_max > 0:
        with open(f"{fol}/BCCON.INC", "w", encoding="utf8") as f:
            f.write(HEADER)
            f.write("BCCON\n")
            f.write("\n".join(sbound))
            f.write("\n/\n")
        for i, days in enumerate(sdays):
            with open(f"{fol}/bc/BCPROP{i}.INC", "w", encoding="utf8") as f:
                f.write(HEADER)
                f.write(f"-- No. days = {days:.2f}\n")
                f.write("BCPROP\n")
                f.write("".join(sbc[i]))
                f.write("/\n")
    with open(f"{fol}/OPERNUM_EXPRECCS.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("OPERNUM\n")
        f.write("".join(compact_format_numeric(sopn)))
        f.write("/\n")


def find_ij_orientation(
    sgrid: OpmGrid,
) -> tuple[int, int]:
    """Right or left grid oriented"""
    origin = sgrid.xyz_from_ijk(0, 0, 0, True)
    y1 = origin[1][0]
    y2 = sgrid.xyz_from_ijk(0, 1, 0, True)[1][0]
    x1 = origin[1][0]
    x2 = sgrid.xyz_from_ijk(1, 0, 0, True)[1][0]
    if y2 < y1:
        mly = 1
    else:
        mly = -1
    if x2 < x1:
        mlx = 1
    else:
        mlx = -1
    return mly, mlx


def extract_site_borders(
    sgrid: OpmGrid,
    sdim: NDArray,
    sinit: OpmFile,
    srst: OpmRestart,
    boundaries: list[int],
    explicit: bool,
    mly: int,
    mlx: int,
    sfip: NDArray,
) -> SiteBorders:
    """Extract the site border"""
    spres = []
    sai = []
    sbound = []
    gc = 0
    sxn, syn, szn, sfn, stn = [], [], [], [], []
    sxw, syw, szw, sfw, stw = [], [], [], [], []
    sxs, syl, szs, sfs, sts = [], [], [], [], []
    sxe, sye, sze, sfe, ste = [], [], [], [], []
    d_z = 0.5 * sinit["DZ"]
    pressure0 = srst["PRESSURE", 0]
    if boundaries[0] > -1:
        j = boundaries[0]
        for k in range(sdim[2]):
            for i in range(sdim[0]):
                ind = sgrid.active_index(i, j, k)
                if ind > -1:
                    sai.append(gc)
                    xyz = np.mean(sgrid.xyz_from_ijk(i, j, k, True), axis=1)
                    d_y = 0.5 * sinit["DY"][ind]
                    sbound.append(f"{gc+1} {i+1} {i+1} {j+1} {j+1} {k+1} {k+1} 'J-' /")
                    sxn.append(xyz[0])
                    syn.append(xyz[1] + mly * d_y)
                    szn.append(xyz[2])
                    sfn.append(sfip[ind])
                    stn.append(xyz[2] - d_z[ind])
                if not explicit:
                    spres.append(pressure0[ind])
                gc += 1
    if boundaries[1] > -1:
        i = sdim[0] - 1 - boundaries[1]
        for k in range(sdim[2]):
            for j in range(sdim[1]):
                ind = sgrid.active_index(i, j, k)
                if ind > -1:
                    sai.append(gc)
                    xyz = np.mean(sgrid.xyz_from_ijk(i, j, k, True), axis=1)
                    d_x = 0.5 * sinit["DX"][ind]
                    sbound.append(f"{gc+1} {i+1} {i+1} {j+1} {j+1} {k+1} {k+1} 'I' /")
                    sxw.append(xyz[0] - mlx * d_x)
                    syw.append(xyz[1])
                    szw.append(xyz[2])
                    sfw.append(sfip[ind])
                    stw.append(xyz[2] - d_z[ind])
                if not explicit:
                    spres.append(pressure0[ind])
                gc += 1
    if boundaries[2] > -1:
        j = sdim[1] - 1 - boundaries[2]
        for k in range(sdim[2]):
            for i in range(sdim[0]):
                ii = sdim[0] - i - 1
                ind = sgrid.active_index(ii, j, k)
                if ind > -1:
                    sai.append(gc)
                    xyz = np.mean(sgrid.xyz_from_ijk(ii, j, k, True), axis=1)
                    d_y = 0.5 * sinit["DY"][ind]
                    sbound.append(f"{gc+1} {ii+1} {ii+1} {j+1} {j+1} {k+1} {k+1} 'J' /")
                    sxs.append(xyz[0])
                    syl.append(xyz[1] - mly * d_y)
                    szs.append(xyz[2])
                    sfs.append(sfip[ind])
                    sts.append(xyz[2] - d_z[ind])
                if not explicit:
                    spres.append(pressure0[ind])
                gc += 1
    if boundaries[3] > -1:
        i = boundaries[3]
        for k in range(sdim[2]):
            for j in range(sdim[1]):
                jj = sdim[1] - j - 1
                ind = sgrid.active_index(i, jj, k)
                if ind > -1:
                    sai.append(gc)
                    xyz = np.mean(sgrid.xyz_from_ijk(i, jj, k, True), axis=1)
                    d_x = 0.5 * sinit["DX"][ind]
                    sbound.append(
                        f"{gc+1} {i+1} {i+1} {jj+1} {jj+1} {k+1} {k+1} 'I-' /"
                    )
                    sxe.append(xyz[0] + mlx * d_x)
                    sye.append(xyz[1])
                    sze.append(xyz[2])
                    sfe.append(sfip[ind])
                    ste.append(xyz[2] - d_z[ind])
                if not explicit:
                    spres.append(pressure0[ind])
                gc += 1
    # fmt: off
    return SiteBorders(
        spres,sai,sbound,
        sxn,syn,szn,sfn,stn,
        sxw,syw,szw,sfw,stw,
        sxs,syl,szs,sfs,sts,
        sxe,sye,sze,sfe,ste
    )
    # fmt: on
