# SPDX-FileCopyrightText: 2023-2026 NORCE Research AS
# SPDX-License-Identifier: GPL-3.0
# pylint: disable=R0912

"""Utiliy functions for necessary files and variables to run OPM Flow"""

import csv
import os
import subprocess

from mako.template import Template


def write_files(dic, reservoir, iteration=0):
    """Write opm-related reference files by running mako templates"""
    name = "site" if "site" in reservoir else reservoir
    name = "regional" if "regional" in name else name
    relpath = ""
    if iteration > 0:
        relpath = "../regional/"
    mytemplate = Template(filename=f"{dic['pat']}/templates/decks/{name}.mako")
    var = {"dic": dic, "reservoir": name, "inc": reservoir, "relpath": relpath}
    filledtemplate = mytemplate.render(**var)
    with open(
        f"{dic[f'fpre{reservoir}']}{reservoir.upper()}.DATA", "w", encoding="utf8"
    ) as file:
        file.write(filledtemplate)
    if name == "regional" and dic["iterations"] > 0:
        for mlt in ["X", "Y", "X-", "Y-"]:
            tmp = [f"{val:E}" for val in dic[f"{name}_mult{mlt.lower()}"]]
            tmp = [f"MULT{mlt}\n"] + compact_format(tmp) + ["/"]
            with open(
                f"{dic[f'fpre{reservoir}']}{reservoir.upper()}_MULT{mlt}.INC",
                "w",
                encoding="utf8",
            ) as file:
                file.write("".join(tmp))
    if iteration > 0:
        return
    if name != "site":
        kwrs = ["fipnum"]
        if name == "regional":
            kwrs += ["opernum"]
        for kwr in kwrs:
            dic[f"{name}_{kwr}"] = compact_format(dic[f"{name}_{kwr}"])
            dic[f"{name}_{kwr}"].insert(0, f"{kwr.upper()}\n")
            dic[f"{name}_{kwr}"].append("/")
            with open(
                f"{dic[f'fpre{reservoir}']}{reservoir.upper()}_{kwr.upper()}.INC",
                "w",
                encoding="utf8",
            ) as file:
                file.write("".join(dic[f"{name}_{kwr}"]))
            dic[f"{name}_{kwr}"] = dic[f"{name}_{kwr}"][1:-1]
    mytemplate = Template(
        filename=f"{dic['pat']}/templates/common/saturation_functions.mako"
    )
    var = {"dic": dic, "reservoir": reservoir}
    filledtemplate = mytemplate.render(**var)
    whr = f"{dic['fol']}/preprocessing/{reservoir}/saturation_functions.py"
    with open(whr, "w", encoding="utf8") as file:
        file.write(filledtemplate)
    os.chmod(whr, 0o755)
    prosc = subprocess.run(
        ["python", whr, "-r", reservoir], check=True, capture_output=True, text=True
    )
    if prosc.returncode != 0:
        raise ValueError(f"Invalid result: {prosc.returncode}")
    os.remove(whr)
    write_grid(dic, name, reservoir)


def write_grid(dic, name, reservoir):
    """Write the corner-point grid"""
    grid, tmp = [], []
    grid.append(
        "-- This file was generated by expreccs https://github.com/cssr-tools/expreccs\n"
    )
    grid.append("-- Copyright (C) 2023-2026 NORCE Research AS\n")
    grid.append("COORD\n")
    if name in ["reference", "regional"]:
        for j in range(dic[f"{name}_num_cells"][1] + 1):
            for i in range(dic[f"{name}_num_cells"][0] + 1):
                tmp.append(
                    f"{dic[f'{name}_xmx'][i]:E} {dic[f'{name}_ymy'][j]:E} 0 "
                    f"{dic[f'{name}_xmx'][i]:E} {dic[f'{name}_ymy'][j]:E} "
                    f"{dic[f'{name}_dims'][2]:E} "
                )
    else:
        for xcor, ycor in zip(dic["site_xc"], dic["site_yc"]):
            tmp.append(
                f"{xcor:E} {ycor:E} 0 {xcor:E} {ycor:E} {dic[f'{name}_dims'][2]:E} "
            )
    grid += compact_format("".join(tmp).split())
    grid.append("/\n")
    grid.append("ZCORN\n")
    lol, tmp = [], []
    with open(f"{dic['pat']}/templates/common/grid.mako", "r", encoding="utf8") as file:
        for i, row in enumerate(csv.reader(file, delimiter="#")):
            if i == 3:
                lol.append(f"    return {dic['z_xy']}")
            elif len(row) == 0:
                lol.append("")
            else:
                lol.append(row[0])
    var = {"dic": dic, "reservoir": name}
    gridtemplate = Template(text="\n".join(lol)).render(**var)
    grid += compact_format("".join(gridtemplate).split())
    grid.append("/")
    with open(
        f"{dic[f'fpre{reservoir}']}{reservoir.upper()}_GRID.INC", "w", encoding="utf8"
    ) as file:
        file.write("".join(grid))


def compact_format(values):
    """Use the 'n*x' notation to write repited values to save storage"""
    n, value0, tmp = 0, float(values[0]), []
    if len(values) == 1:
        value0 = float(values[0])
        if value0 == 0:
            return ["0 "]
        if value0.is_integer():
            return [f"{int(value0)} "]
        return [f"{value0} "]
    for value in values:
        valuef = float(value)
        if value0 != valuef:
            if value0 == 0:
                tmp.append(f"{n}*0 " if n > 1 else "0 ")
            elif value0.is_integer():
                tmp.append(f"{n}*{int(value0)} " if n > 1 else f"{int(value0)} ")
            else:
                tmp.append(f"{n}*{value0} " if n > 1 else f"{value0} ")
            n = 1
            value0 = valuef
        else:
            n += 1
    if value0 == float(values[-1]):
        if value0 == 0:
            tmp.append(f"{n}*0 " if n > 1 else "0 ")
        elif value0.is_integer():
            tmp.append(f"{n}*{int(value0)} " if n > 1 else f"{int(value0)} ")
        else:
            tmp.append(f"{n}*{value0} " if n > 1 else f"{value0} ")
    return tmp


def write_properties(dic):
    """Write some numpy files used in the plotting routine"""
    dic["schedule_r"], dic["schedule_s"] = [0], [0]
    for nrst in dic["inj"]:
        for _ in range(round(nrst[0][0] / nrst[0][1])):
            dic["schedule_r"].append(dic["schedule_r"][-1] + nrst[0][1] * 86400.0)
        for _ in range(round(nrst[0][0] / nrst[0][2])):
            dic["schedule_s"].append(dic["schedule_s"][-1] + nrst[0][2] * 86400.0)


def write_folders(dic):
    """Make the output folders"""
    if not os.path.exists(f"{dic['fol']}"):
        os.makedirs(f"{dic['fol']}", exist_ok=True)
    if not dic["subfolders"]:
        return
    for fil in ["preprocessing", "simulations"]:
        if not os.path.exists(f"{dic['fol']}/{fil}"):
            os.makedirs(f"{dic['fol']}/{fil}", exist_ok=True)
    if dic["mode"] in ["all"]:
        for fil in ["reference", "regional", f"site_{dic['site_bctype'][0]}"]:
            if not os.path.exists(f"{dic['fol']}/preprocessing/{fil}"):
                os.makedirs(f"{dic['fol']}/preprocessing/{fil}", exist_ok=True)
            if not os.path.exists(f"{dic['fol']}/simulations/{fil}"):
                os.makedirs(f"{dic['fol']}/simulations/{fil}", exist_ok=True)
    else:
        names = []
        if dic["mode"] in ["reference", "regional"]:
            names = [dic["mode"]]
        elif dic["mode"] == "regional_site":
            names = ["regional", f"site_{dic['site_bctype'][0]}"]
        elif dic["mode"] == "site":
            names = [f"site_{dic['site_bctype'][0]}"]
        for name in names:
            if not os.path.exists(f"{dic['fol']}/preprocessing/{name}"):
                os.makedirs(f"{dic['fol']}/preprocessing/{name}", exist_ok=True)
            if not os.path.exists(f"{dic['fol']}/simulations/{name}"):
                os.makedirs(f"{dic['fol']}/simulations/{name}", exist_ok=True)
